name: pori
recipe: drupal7
config:
  php: '7.2'
  via: nginx
  webroot: web
  config:
    vhosts: ./.lando/drupal7.conf

services:
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    run_as_root:
        - /app/.lando/adminer.sh
    portforward: true
  appserver:
    build_as_root:
      - "apt-get update -y"
      - "apt-get install python-yaml -y"
    build:
      - /app/.lando/build.sh
    overrides:
      environment:
        WKV_SITE_ENV: lando
        DB_PASS_DRUPAL: drupal7
        DB_USER_DRUPAL: drupal7
        DB_HOST_DRUPAL: database
        DB_NAME_DRUPAL: drupal7
  database:
    type: mariadb:10.2
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  memcached:
    type: memcached
    portforward: true
    run:
      - /bin/sh -c '/opt/bitnami/memcached/bin/memcached start -d'
  node:
    type: node
  # redis:
  #   type: redis
  #   portforward: true 
  solr:
    type: solr:5
    config:
      dir: web/sites/all/modules/contrib/search_api_solr/solr-conf/5.x

tooling:
  build:
    description: Build the local site.
    cmd:
      - appserver: /app/.lando/build.sh
  build.sh:
    description: Run build.sh commands.
    cmd:
      - appserver: /app/build.sh
  phpcbf:
    description: Run phpcbf commands.
    cmd:
      - appserver: /app/vendor/bin/phpcbf
  phpcs:
    description: Run phpcs commands.
    cmd:
      - appserver: /app/vendor/bin/phpcs
  node:
    service: node
  npm:
    service: node
  syncdb:
    description: Synchronize local db with selected env (lando syncdb stage/prod).
    cmd:
      - appserver: /app/.lando/syncdb.sh
      # - appserver: /app/.lando/update.sh
  update:
    description: Update local site with development settings.
    cmd:
      - appserver: /app/.lando/update.sh

proxy:
  appserver_nginx:
    - pori.lndo.site
    - businesspori.lndo.site
    - visitpori.lndo.site
  mailhog:
    - pori-mail.lndo.site
  adminer:
    - pori-adminer.lndo.site

events:
  post-db-import:
    - appserver: /app/.lando/update.sh

# Tested with Lando version.
version: v3.0.0-rc.23
