name: pori
recipe: drupal7
config:
  php: '7.2'
  via: nginx
  webroot: web
  composer_version: 1-latest
  drush: ^8
  xdebug: off
  config:
    vhosts: ./.lando/drupal7.conf
    php: .lando/php.ini

services:
  adminer:
    type: compose
    services:
      image: dehy/adminer:4.7
      command: /bin/s6-svscan /etc/services.d
    run_as_root:
        - /app/.lando/adminer.sh
    portforward: true
  appserver:
    build_as_root:
      - chmod -R a+w /app/web/
    build:
      - composer install
      - /app/.lando/build.sh
    overrides:
      environment:
        WKV_SITE_ENV: lando
        DB_PASS_DRUPAL: drupal7
        DB_USER_DRUPAL: drupal7
        DB_HOST_DRUPAL: database
        DB_NAME_DRUPAL: drupal7
        SAML_ADMINPASS: admin-123
        SAML_SECRETSALT: salty-cracker-1
        XDEBUG_MODE:
        PHP_IDE_CONFIG: "serverName=appserver"
  database:
    type: mariadb:10.2
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  memcached:
    type: memcached
    portforward: true
  node:
    type: node
    globals:
      gulp-cli: latest
      bower: latest
  solr:
    type: solr:5
    config:
      dir: web/sites/all/modules/contrib/search_api_solr/solr-conf/5.x

tooling:
  build:
    description: Build the local site.
    cmd:
      - appserver: /app/.lando/build.sh
  compile:
    description: Compile the themes.
    cmd:
      - node: /app/.lando/node.sh
  bower:
    service: node
  gulp:
    service: node
  phpcbf:
    description: Run phpcbf commands.
    cmd:
      - appserver: /app/vendor/bin/phpcbf
  phpcs:
    description: Run phpcs commands.
    cmd:
      - appserver: /app/vendor/bin/phpcs
  node:
    service: node
  npm:
    service: node
  syncdb:
    description: Synchronize local db with selected env (lando syncdb stage/prod).
    cmd:
      - appserver: /app/.lando/syncdb.sh
  update:
    description: Update local site with development settings.
    cmd:
      - appserver: /app/.lando/update.sh
  xdebug:
    description: Loads Xdebug in the selected mode.
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root
  yarn:
    service: node

proxy:
  appserver_nginx:
    - pori.lndo.site
    - businesspori.lndo.site
    - visitpori.lndo.site
  mailhog:
    - pori-mail.lndo.site
  adminer:
    - pori-adminer.lndo.site

env_file:
  - .lando/lando.env

# Tested with Lando version.
version: v3.0.23
