---

default:

  # It's D7, but build.sh doesn't support D7 composer builds.
  drupal_version: d8

  profile: kadaprofile
  site: KADA

  aliases:
    - local

  # In development environments we want to use symlinks, note settings.php
  link:
    - files: web/sites/default/files

  # We can provide local commands or override global ones.
  local_commands:
    new:
      - verify: "Type yes to verify you want to build a new installation: "
      - shell: ln -sfv /vagrant/drupal/drush/pori-kada.aliases.drushrc.php /home/vagrant/.drush/pori-kada.aliases.drushrc.php
      - shell: chmod -R a+w web
      - make
      # - backup
      # Install dev modules
      # - purge
      # - finalize
      # - install
      - cleanup
      - drush: cc drush
      #- drush: composer-json-rebuild -y
      #- drush: composer-manager update -y
      - shell: sudo systemctl restart nginx php-fpm varnish memcached


    # Running command "./build.sh update" without environment or with "vagrant" as environment "./build.sh update vagrant" will also make sure that stage_file_proxy is enabled.
    # Basic site update functionality
    update:
      - shell: ln -sfv /vagrant/drupal/drush/pori-kada.aliases.drushrc.php /home/vagrant/.drush/pori-kada.aliases.drushrc.php
      - shell: chmod -R a+w web
      - make
      - finalize
      - update
      - cleanup
      - drush: en devel stage_file_proxy -y
      - drush: cc drush
      - drush: uli
      #- drush: composer-json-rebuild -y
      #- drush: composer-manager update -y
      - shell: sudo systemctl restart nginx php-fpm varnish memcached

# Lando environment:
lando:
lando:
  # Allow development modules to be installed.
  allow_composer_dev: true

  # Symlink files folder. This is generic location for both dev and stage environments.
  link:
    - files: web/sites/default/files

  # These commands will be used in all environments unless they are overridden.
  local_commands:
    # Set up a new build
    build:
      - make

# Test environment:
develop:

  # Test environment only symlinks files
  link:
    - /var/www/pori.dev.wunder.io/files: web/sites/default/files

  # Other files are copied, note settings.php
  copy:
    - conf/settings.php: web/sites/default/settings.local.php
    - conf/dev.radioactivity-bootstrap.cfg.inc: web/sites/default/radioactivity-bootstrap.cfg.inc

  local_commands:
    build:
      - shell: chmod -R a+w web
      - make
      - finalize

    update:
      - update
      - cleanup
      - drush: en devel -y
      - drush: fra -y
      - drush: cc drush
      # - drush: composer-json-rebuild -y
      # - drush: composer-manager update -y
      - shell: chmod -R a-w web
      - shell: sudo systemctl restart nginx php-fpm varnish memcached

# Test environment:
stage:


  # Test environment only symlinks files
  link:
    - /var/www/pori.stage.wunder.io/files: web/sites/default/files

  # Other files are copied, note settings.php
  copy:
    - conf/settings.php: web/sites/default/settings.local.php
    - conf/dev.radioactivity-bootstrap.cfg.inc: web/sites/default/radioactivity-bootstrap.cfg.inc

  local_commands:
    build:
      - shell: chmod -R a+w web
      - make
      - finalize

    update:
      - update
      - cleanup
      - drush: omega-revert kada
      - drush: en devel -y
      - drush: fra -y
      - drush: cc drush
      # - drush: composer-json-rebuild -y
      # - drush: composer-manager update -y
      - shell: chmod -R a-w web
      - shell: sudo systemctl restart nginx php-fpm varnish memcached

prod:


  # Test environment only symlinks files
  link:
    - /var/www/pori.prod.wunder.io/files: web/sites/default/files

  # Other files are copied, note settings.php
  copy:
    - conf/settings.php: web/sites/default/settings.local.php
    - conf/dev.radioactivity-bootstrap.cfg.inc: web/sites/default/radioactivity-bootstrap.cfg.inc

  local_commands:
    build:
      - shell: chmod -R a+w web
      - make
      - finalize

    update:
      - update
      - cleanup
      - drush: omega-revert kada
      - drush: dis devel -y
      - drush: fra -y
      - drush: cc drush
      #- drush: composer-json-rebuild -y
      #- drush: composer-manager update -y
      - shell: chmod -R a-w web
      - drush: cc all
      - shell: sudo systemctl restart nginx php-fpm varnish memcached
